[programs.mainnet]
staking_program = "2nzuuPMGzrwtzXXU6PXP3dcTj24gJKS6uG8AsCuSs2mf"

[registry]
url = "https://anchor.projectserum.com"

[provider]

cluster = "mainnet"
#cluster = "http://127.0.0.1:8899"
wallet = "/home/fury/.config/solana/id.json"
#wallet = "./test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
